set(_CATKIN_CURRENT_PACKAGE "robot_pan_control")
set(robot_pan_control_VERSION "0.0.0")
set(robot_pan_control_MAINTAINER "lql <lql@todo.todo>")
set(robot_pan_control_PACKAGE_FORMAT "2")
set(robot_pan_control_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(robot_pan_control_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(robot_pan_control_BUILDTOOL_DEPENDS "catkin")
set(robot_pan_control_BUILDTOOL_EXPORT_DEPENDS )
set(robot_pan_control_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(robot_pan_control_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(robot_pan_control_TEST_DEPENDS )
set(robot_pan_control_DOC_DEPENDS )
set(robot_pan_control_URL_WEBSITE "")
set(robot_pan_control_URL_BUGTRACKER "")
set(robot_pan_control_URL_REPOSITORY "")
set(robot_pan_control_DEPRECATED "")